#
# Ansible Playbook: create or delete dns A record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: 1.Before - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"

    - block:
      - name: 2.Create A record in Route53
        route53:
          type: A
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: create_a_record
      when: command == 'create' 
            and 
            type == 'A'
            and
            routing_policy == 'false'

    - block:
      - name: 3.Create A record and routing policy in Route53
        route53:
          type: A
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          # Routing policy
          weight: "{{ weight }}"
          identifier: "{{ set_id }}"
#          health_check: "{{ health_check_id }}"
        register: create_a_record___r
      when: command == 'create' 
            and 
            type == 'A'
            and 
            routing_policy == 'true'

    - block:
      - name: 4.Change A record in Route53
        route53:
          type: A
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          overwrite: true
        register: change_a_record
      when: command == 'change' 
            and 
            type == 'A'
            and 
            routing_policy == 'false'

    - block:
      - name: 5.Change A record and routing policy in Route53
        route53:
          type: A
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          # Routing policy
          weight: "{{ weight }}"
          identifier: "{{ set_id }}"
#          health_check: "{{ health_check_id }}"
          overwrite: true
        register: change_a_record___r
      when: command == 'change' 
            and 
            type == 'A'
            and 
            routing_policy == 'true'

    - block:
      - name: 6.Get A record in Route53.
        route53:
          type: A
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: command == 'delete'
            and 
            type == 'A'

    - block:
      - name: 7.Delete dns A record in Route53.
        route53:
          type: A
          state: absent
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: delete_a_record
      when: command == 'delete'
            and 
            type == 'A'

    - block:
      - name: 8.Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: seconds=60
      when: (create_a_record is not skipped)
             or
            (create_a_record___r is not skipped)
             or
            (change_a_record is not skipped)
             or
            (change_a_record___r is not skipped)
             or
            (delete_a_record is not skipped)

    - block:
      - name: 9.After - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (create_a_record is not skipped)
             or
            (create_a_record___r is not skipped)
             or
            (change_a_record is not skipped)
             or
            (change_a_record___r is not skipped)
             or
            (delete_a_record is not skipped)

    - block:
      - name: 10.Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_a_record|skipped)
             and
            (create_a_record___r|skipped)
             and
            (change_a_record|skipped)
             and
            (change_a_record___r|skipped)
             and
            (delete_a_record|skipped)
