#
# Ansible Playbook: create or delete dns A record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Set hosted zones dns A record in Route53
        route53:
          type: A
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
      when: private_hosted_zone == 'false' and routing_policy == 'false'

    - block:
      - name: Set hosted zones dns A record and routing policy in Route53
        route53:
          type: A
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
          # Routing policy
          weight: "{{ weight }}"
          identifier: "{{ set_id }}"
#          health_check: "{{ health_check_id }}"
      when: private_hosted_zone == 'false' and routing_policy == 'true'

    - block:
      - name: Set private hosted zones dns A record in Route53
        route53:
          type: A
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
          private_zone: "{{ private_hosted_zone }}"
      when: private_hosted_zone == 'true' and routing_policy == 'false'

    - block:
      - name: Set private hosted zones dns A and routing policy  record in Route53
        route53:
          type: A
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
          private_zone: "{{ private_hosted_zone }}"
          # Routing policy
          weight: "{{ weight }}"
          identifier: "{{ set_id }}"
#          health_check: "{{ health_check_id }}"
      when: private_hosted_zone == 'true' and routing_policy == 'true'
