---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Set public dns A record in Route53
      route53:
        command: "{{ command }}"
        zone: "{{ zone }}"
        record: "{{ record }}"
        value: "{{ value }}"
        ttl: 300
        type: A
