#
# Ansible Playbook: create or delete dns A-Alias, CNAME-Alias record in AWS Route53
#
#  AレコードのAliasは対応済みだが、CNAMEのAliasはまだ未対応
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Before - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"

    - block:
      - name: Create dns A-Alias record in Route53
        route53:
          type: A
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ elb_dns_name }}"
          ttl: "{{ ttl }}"
          alias: True
          alias_hosted_zone_id: "{{ elb_hosted_zone_id }}"
          private_zone: "{{ private_hosted_zone }}"
        register: create_a_alias_record
      when: command == 'create'

    - block:
      - name: Change dns Alias record in Route53.
        route53:
          type: A
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ elb_dns_name }}"
          ttl: "{{ ttl }}"
          alias: True
          alias_hosted_zone_id: "{{ elb_hosted_zone_id }}"
          private_zone: "{{ private_hosted_zone }}"
          overwrite: true
        register: change_a_alias_record
      when: command == 'change' 
       
    - block:
      - name: Get dns A record in Route53.
        route53:
          type: A
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: command == 'delete'

    - block:
      - name: Delete dns A record in Route53.
        route53:
          type: A
          state: absent
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          alias: True
          alias_hosted_zone_id: "{{ rec.set.alias_hosted_zone_id }}"
          private_zone: "{{ private_hosted_zone }}"
        register: delete_a_alias_record
      when: command == 'delete'

    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: seconds=30
      when: (create_a_alias_record is not skipped)
             or
            (change_a_alias_record is not skipped)
             or
            (delete_a_alias_record is not skipped)

    - block:
      - name: After - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (create_a_alias_record is not skipped)
             or
            (change_a_alias_record is not skipped)
             or
            (delete_a_alias_record is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_a_alias_record|skipped)
             and
            (change_a_alias_record|skipped)
             and
            (delete_a_alias_record|skipped)
