#
# Ansible Playbook: create or delete dns CNAME record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Set dns CNAME record in Route53, Hosted zone.
        route53:
          type: CNAME
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
      when: private_hosted_zone == 'false'

    - block:
      - name: Set dns CNAME record in Route53, Private hosted zone.
        route53:
          type: CNAME
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
      when: private_hosted_zone == 'true'
