#
# Ansible Playbook: create or delete dns CNAME record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Before - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"

    - block:
      - name: Create dns CNAME record in Route53.
        route53:
          type: CNAME
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: create_cname_record
      when: command == 'create'

    - block:
      - name: Change dns CNAME record in Route53.
        route53:
          type: CNAME
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          overwrite: true
        register: change_cname_record
      when: command == 'change' 
       
    - block:
      - name: Get dns CNAME record in Route53.
        route53:
          type: CNAME
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: command == 'delete'

    - block:
      - name: Delete dns CNAME record in Route53.
        route53:
          type: CNAME
          state: absent
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: delete_cname_record
      when: command == 'delete'

    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: seconds=60
      when: (create_cname_record is not skipped)
             or
            (change_cname_record is not skipped)
             or
            (delete_cname_record is not skipped)

    - block:
      - name: After - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (create_cname_record is not skipped)
             or
            (change_cname_record is not skipped)
             or
            (delete_cname_record is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_cname_record|skipped)
             and
            (change_cname_record|skipped)
             and
            (delete_cname_record|skipped)
