- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
#    - name: Create ec2 instance
#      ec2:
#        key_name: ymatsu_aws_ssh_keys
#        instance_type: t2.micro
#        image: ami-28ddc154
#        monitoring: yes
#        wait: yes
#        region: ap-northeast-1
#        group_id: sg-c133bea4
#        vpc_subnet_id: subnet-9dd921c4
#        assign_public_ip: yes
#        instance_tags: 
#          Name: ansible1
#      register: ec2
#
    - name: Set Public DNS to CNAME in Route53
      route53:
        command: create
        zone: ac-operations.com.
        record: ansible2.ac-operations.com
        type: A
        value: 22.22.22.22
#        type: CNAME
#        value: "{{ item.public_dns_name }}"
        overwrite: yes
        ttl: 300
      with_items: ec2.instances
