#
# Ansible Playbook: get dns records in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Get dns records in Route53
        route53:
          type: "{{ type }}"
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: private_hosted_zone == 'false'

    - block:
      - name: Get dns records in Route53
        route53:
          type: "{{ type }}"
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: private_hosted_zone == 'true'
