#
# Ansible Playbook: get dns records in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - lock:
      - name: Get hosted zone dns record in Route53
        route53:
          type: "{{ type }}"
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: get_record
      when: private_hosted_zone == 'false'

    - lock:
      - name: Get private hosted zone dns record in Route53
        route53:
          type: "{{ type }}"
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: pri_get_record
      when: private_hosted_zone == 'true'

    - lock:
      - name: Exception Handler - Invalid parameter resources
        route53_facts:
        failed_when: true
      when: (get_record|skipped)
             and
            (pri_get_record|skipped)
