- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
#    - name: Create ec2 instance
#      ec2:
#        key_name: ymatsu_aws_ssh_keys
#        instance_type: t2.micro
#        image: ami-28ddc154
#        monitoring: yes
#        wait: yes
#        region: ap-northeast-1
#        group_id: sg-c133bea4
#        vpc_subnet_id: subnet-9dd921c4
#        assign_public_ip: yes
#        instance_tags: 
#          Name: ansible1
#      register: ec2
#
    - name: Set Public DNS to CNAME in Route53
      route53:
        command: "{{ command }}"
        zone: "{{ zone }}"
        record: "{{ record }}"
        type: "{{ type }}"
        value: "{{ value }}"
        overwrite: yes
        ttl: "{{ ttl }}"
      with_items: ec2.instances
