#
# Ansible Playbook: create or delete dns MX record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Create dns MX record in Route53.
        route53:
          type: MX
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: create_mx_record
      when: command == 'create'

    - block:
      - name: Change dns MX record in Route53.
        route53:
          type: MX
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          overwrite: true
        register: change_mx_record
      when: command == 'change' 
       
    - block:
      - name: Get dns MX record in Route53.
        route53:
          type: MX
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: command == 'delete'

    - block:
      - name: Delete dns MX record in Route53.
        route53:
          type: MX
          state: absent
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: delete_mx_record
      when: command == 'delete'

    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: seconds=30
      when: (create_mx_record is not skipped)
             or
            (change_mx_record is not skipped)
             or
            (delete_mx_record is not skipped)

    - block:
      - name: DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (create_mx_record is not skipped)
             or
            (change_mx_record is not skipped)
             or
            (delete_mx_record is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_mx_record|skipped)
             and
            (change_mx_record|skipped)
             and
            (delete_mx_record|skipped)
