#
# Ansible Playbook: create or delete dns MX record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Set hosted zones dns MX record in Route53
        route53:
          type: MX
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
        register: mx_record
      when: private_hosted_zone == 'false'

    - block:
      - name: Set private hosted zones dns MX record in Route53
        route53:
          type: MX
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ value }}"
          ttl: "{{ ttl }}"
          overwrite: true
          private_zone: "{{ private_hosted_zone }}"
        register: mx_record___p
      when: private_hosted_zone == 'true'

    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: minutes=1
      when: (mx_record is not skipped)
             or
            (mx_record___p is not skipped)

    - block:
      - name: DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (mx_record is not skipped)
             or
            (mx_record___p is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (mx_record|skipped)
             and
            (mx_record___p|skipped)
