#
# Ansible Playbook: create or delete dns TXT record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Before - DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"

    - block:
      - name: Create dns TXT record in Route53
        route53:
          type: TXT
          command: create
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: create_txt_record
      when: command == 'create' 
       
    - block:
      - name: Change dns TXT record in Route53
        route53:
          type: TXT
          command: present
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          private_zone: "{{ private_hosted_zone }}"
          overwrite: true
        register: change_txt_record
      when: command == 'change' 
       
    - block:
      - name: Get dns TXT record in Route53.
        route53:
          type: TXT
          state: get
          zone: "{{ zone }}"
          record: "{{ record }}"
          private_zone: "{{ private_hosted_zone }}"
        register: rec
      when: command == 'delete'

    - block:
      - name: Delete dns TXT record in Route53.
        route53:
          type: TXT
          state: absent
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          private_zone: "{{ private_hosted_zone }}"
        register: delete_txt_record
      when: command == 'delete'

    - block:
      - name: Wait until it is reflected TXT record "{{ record }}"
        pause: seconds=30
      when: (create_txt_record is not skipped)
             or
            (change_txt_record is not skipped)
             or
            (delete_txt_record is not skipped)

    - block:
      - name: DNS lookup that TXT record in Route53
        debug: msg="The dns lookup for type TXT, record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype=TXT" ) }}"
      when: (create_txt_record is not skipped)
             or
            (change_txt_record is not skipped)
             or
            (delete_txt_record is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_txt_record|skipped)
             and
            (change_txt_record|skipped)
             and
            (delete_txt_record|skipped)
