#
# Ansible Playbook: create or delete dns TXT record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Create dns TXT record in Route53, Hosted zone.
        route53:
          type: TXT
          command: create
          zone: "{{ create.zone }}"
          record: "{{ create.record }}"
          value: '"{{ create.value }}"'
          ttl: "{{ create.ttl }}"
          overwrite: true
        register: create_txt_record
      when: create.command == 'create' and create.private_hosted_zone == 'false' and create is defined

    - block:
      - name: Create dns TXT record in Route53, Private hosted zone.
        route53:
          type: TXT
          command: create
          zone: "{{ create.zone }}"
          record: "{{ create.record }}"
          value: '{{ create.value }}'
          ttl: "{{ create.ttl }}"
          overwrite: true
          private_zone: "{{ create.private_hosted_zone }}"
        register: create_txt_record___p
      when: create.command == 'create' and create.private_hosted_zone == 'true' and create is defined

    - block:
      - name: Get dns TXT record in Route53, Hosted zone.
        route53:
          state: get
          zone: "{{ delete.zone }}"
          record: "{{ delete.record }}"
          type: "{{ delete.type }}"
          private_zone: "{{ delete.private_hosted_zone }}"
        register: rec
      when: delete.command == 'delete' and delete is defined

    - block:
      - name: Delete dns TXT record in Route53, Hosted zone.
        route53:
          type: TXT
          state: absent
          zone: "{{ delete.zone }}"
          record: "{{ rec.set.record }}"
          value: "{{ rec.set.value }}"
          ttl: "{{ rec.set.ttl }}"
          private_zone: "{{ delete.private_hosted_zone }}"
        register: delete_txt_record
      when: delete.command == 'delete' and delete is defined


    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: minutes=1
      when: (create_txt_record is not skipped)
             or
            (create_txt_record___p is not skipped)
             or
            (delete_txt_record is not skipped)

    - block:
      - name: DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (create_txt_record is not skipped)
             or
            (create_txt_record___p is not skipped)
             or
            (delete_txt_record is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (create_txt_record|skipped)
             and
            (create_txt_record___p|skipped)
             and
            (delete_txt_record|skipped)
