#
# Ansible Playbook: create or delete dns TXT record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Set dns TXT record in Route53, Hosted zone.
        route53:
          type: TXT
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          overwrite: true
      when: private_hosted_zone == 'false'

    - block:
      - name: Set dns TXT record in Route53, Private hosted zone.
        route53:
          type: TXT
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          overwrite: true
          private_zone: "{{ private_hosted_zone }}"
      when: private_hosted_zone == 'true'
