#
# Ansible Playbook: create or delete dns TXT record in AWS Route53
#
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - block:
      - name: Set dns TXT record in Route53, Hosted zone.
        route53:
          type: TXT
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          overwrite: true
        register: txt_record
      when: private_hosted_zone == 'false'

    - block:
      - name: Set dns TXT record in Route53, Private hosted zone.
        route53:
          type: TXT
          command: "{{ command }}"   # create or delete
          zone: "{{ zone }}"
          record: "{{ record }}"
          value: '"{{ value }}"'
          ttl: "{{ ttl }}"
          overwrite: true
          private_zone: "{{ private_hosted_zone }}"
        register: txt_record___p
      when: private_hosted_zone == 'true'

    - block:
      - name: Wait until it is reflected "{{ type }}" record "{{ record }}"
        pause: minutes=1
      when: (txt_record is not skipped)
             or
            (txt_record___p is not skipped)

    - block:
      - name: DNS lookup that {{ type }} record in Route53
        debug: msg="The dns lookup for type "{{ type }}", record "{{ record }}". is {{ lookup('dig', "{{ record }}" , "qtype={{ type }}" ) }}"
      when: (txt_record is not skipped)
             or
            (txt_record___p is not skipped)

    - block:
      - name: Exception Handler - Invalid parameter resources
        route53:
        failed_when: true
      when: (txt_record|skipped)
             and
            (txt_record___p|skipped)
